v = input().split(' ')
v.sort(key=float, reverse=True)
a, b, c = float(v[0]), float(v[1]), float(v[2])
if a >= b + c: print('NAO FORMA TRIANGULO')
else:
    if a**2 == b**2 + c**2: print('TRIANGULO RETANGULO')
    if a**2 > b**2 + c**2: print('TRIANGULO OBTUSANGULO')
    if a**2 < b**2 + c**2: print('TRIANGULO ACUTANGULO')
    if a == b == c: print('TRIANGULO EQUILATERO')
    if (a == b and a != c) or (b == c and b != a) or (c == a and c != b): print('TRIANGULO ISOSCELES')  
